# Generated by Django 5.0 on 2024-01-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appiontmentmodel',
            name='time',
        ),
    ]
